version: '3.8'

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: infrasyncus-janusgraph
    ports:
      - "8182:8182"
    environment:
      - JANUS_PROPS_TEMPLATE=berkeleyje-es
    volumes:
      - janusgraph-data:/opt/janusgraph/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  janusgraph-data:
    driver: local 